version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3306'
    volumes:
      - ./source:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

